# Generated by Django 2.1.7 on 2019-03-02 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EndosImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('url', models.ImageField(upload_to='patient')),
            ],
        ),
        migrations.CreateModel(
            name='EndosPatient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('date_birth', models.DateField(default=False)),
                ('id_number', models.CharField(blank=True, max_length=9)),
                ('anesthesia', models.CharField(max_length=250)),
                ('diagnosis', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='endosimage',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='endosreg.EndosPatient'),
        ),
    ]
