# Generated by Django 2.1.7 on 2019-03-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endosreg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endosimage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
