# Generated by Django 2.1.7 on 2019-03-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endosreg', '0002_auto_20190302_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endosimage',
            name='url',
            field=models.ImageField(upload_to='media/patient'),
        ),
    ]
