# Generated by Django 2.1.7 on 2019-03-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endosreg', '0003_auto_20190302_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endosimage',
            name='url',
            field=models.ImageField(upload_to='patient/'),
        ),
    ]
