# Generated by Django 2.1.7 on 2019-03-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endosreg', '0004_auto_20190302_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endosimage',
            name='url',
            field=models.ImageField(upload_to='static/media/patients'),
        ),
    ]
