# Generated by Django 2.1.7 on 2019-03-03 09:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('endosreg', '0005_auto_20190302_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='endospatient',
            name='diagnosis_date',
            field=models.TextField(default=django.utils.timezone.now, editable=False),
        ),
    ]
