# Generated by Django 2.1.7 on 2019-03-05 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('endosreg', '0008_auto_20190303_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endospatient',
            name='anesthesia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='endostemplates.Anesthesia'),
        ),
    ]
