# Generated by Django 2.1.7 on 2019-03-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endosreg', '0009_auto_20190305_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endosimage',
            name='url',
            field=models.ImageField(blank=True, upload_to='static/media/patients'),
        ),
    ]
