# Generated by Django 2.1.7 on 2019-03-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endosreg', '0010_auto_20190305_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endosimage',
            name='url',
            field=models.ImageField(upload_to='static/media/patients'),
        ),
    ]
