# Generated by Django 2.1.7 on 2019-02-14 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anesthesia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EndoscopyPatients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('date_birth', models.DateField(default=False)),
                ('id_number', models.CharField(blank=True, max_length=9)),
                ('device', models.CharField(max_length=100)),
                ('anesthesia', models.CharField(max_length=250)),
                ('diagnosis', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateDiagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('diagnosis', models.TextField()),
            ],
        ),
    ]
